
management:
    endpoints.web.exposure.include: health, info, metrics, prometheus
    info:
        env.enabled: true
    endpoint:
        health:
            show-details: always
            probes.enabled: true
